######
# ATDD.TestScriptor Build pipeline - Windows x64
######

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  RunVersion: "0.1.$(Build.BuildId)"

steps:
- checkout: self

# Aurelia App

- script: yarn global add aurelia-cli
  displayName: 'Aurelia-CLI install'
  workingDirectory: 'web-ui'

- script: yarn install
  displayName: 'Aurelia App restore'
  workingDirectory: 'web-ui'

- script: yarn build
  displayName: 'Aurelia App build'
  workingDirectory: 'web-ui'

# VSCode extension

- script: yarn global add vsce
  displayName: 'VSCE install'
  workingDirectory: 'vscode-extension'

- script: yarn add fs
  displayName: 'fs install'
  workingDirectory: 'vscode-extension'

- script: yarn install
  displayName: 'VS Ext. restore'
  workingDirectory: 'vscode-extension'
  
- task: PowerShell@2
  displayName: 'VS Ext. Update package.json'
  inputs:
    targetType: 'inline'
    script: '((Get-Content -path ./package.json -Raw) -replace ''"debugMode": true'',''"debugMode": false'') | Set-Content -Path ./package.json'
    workingDirectory: 'vscode-extension'

- script: yarn version --no-git-tag-version --new-version $(RunVersion)
  displayName: 'VS Ext. set version'
  workingDirectory: 'vscode-extension'

- script: yarn package
  displayName: 'VS Ext. package'
  workingDirectory: 'vscode-extension'

# Finalize

- task: CopyFiles@2
  displayName: 'VS Ext. publish'
  inputs:
    SourceFolder: 'vscode-extension'
    Contents: '*.vsix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Final publish'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'ATDD.TestScriptor'
